[mgr]
show_hidden = true

[opener]
edit = [
	{ run = "$EDITOR %s", block = true, desc = "Editor", for = "unix" },
	{ run = "%EDITOR% %s", block = true, desc = "Editor", for = "windows" },
  { run = '$SHELL', block = true, desc = "Terminal", for = "unix" },
  { run = 'nu.exe', block = true, desc = "Terminal", for = "windows" },
]