[metadata]
name = "env"
description = "A channel to select from environment variables"

[source]
command = "$env | transpose key value | each { $in.key + '=' + ($in.value | into string) } | str join (char newline)"
output = "{split:=:1..}"       # output the value

[preview]
command = "echo '{split:=:1..}'"

[ui]
layout = "portrait"
preview_panel = { size = 20, "header" = "{split:=:0|trim}" }

[keybindings]
shortcut = "f3"
