[[packages.windows.core]]
id = "Nushell.Nushell"

[[packages.windows.core]]
name = "dotnet"
command = '& "$env:CHEZMOI_SOURCEDIR/scripts/install-dotnet.ps1"'

[[packages.windows.core]]
id = "Microsoft.VCRedist.2015+.x64"
desc = "Many applications requires these as dependencies, such as Rust (msvc)"

[[packages.windows.core]]
id = "Microsoft.VisualStudio.BuildTools"
desc = "Many applications requires these as dependencies, such as Rust (msvc)"

[[packages.windows.core]]
id = "Chocolatey.Chocolatey"
# Refresh the Path variable so it'd detect the tool in the current terminal session
postcommand = "$env:PATH = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User')"

[[packages.windows.core]]
name = "Scoop"
command = "powershell -Command 'iex \"& {$(irm get.scoop.sh)} -RunAsAdmin\"'"

[[packages.windows.core]]
name = "uv"
desc = "Package manager for Python"
command = 'powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"; $env:Path = "$env:USERPROFILE\.local\bin;$env:Path"'

[[packages.windows.core]]
name = "Aider"
desc = "Installs python version to be used with Aider" # See https://aider.chat/docs/install.html
command = 'uv tool install --force --python python3.12 --with pip aider-chat@latest'

[[packages.windows.core]]
id = "OpenJS.NodeJS"

[[packages.windows.core]]
name = "Rust"
postcommand = '& "$env:CHEZMOI_SOURCEDIR/scripts/install-rust.ps1"'

[[packages.windows.core]]
name = "Rust - Cargo Configuration"
desc = "Package manager for Rust"
# Add Cargo to the PATH if not already
postcommand = 'if (!([Environment]::GetEnvironmentVariable("Path", "User") -split ";" -contains "$env:USERPROFILE\.cargo\bin")) { [Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", "User") + ";$env:USERPROFILE\.cargo\bin", "User"); $env:Path += ";$env:USERPROFILE\.cargo\bin" }'

[[packages.windows.core]]
name = "cargo-binstall"
desc = "Binary package manager for Rust"
command = "cargo install cargo-binstall"

[[packages.windows.core]]
name = "intelli-shell"
command = 'cargo binstall -y intelli-shell --locked'

[[packages.windows.core]]
name = "gittype"
command = 'cargo install gittype'

[[packages.windows.core]]
id = 'tsl0922.ttyd'
postcommand = '& "$env:CHEZMOI_SOURCEDIR/scripts/setup-ttyd.ps1"'

[[packages.windows.core]]
id = 'mitmproxy.mitmproxy'

[[packages.windows.core]]
name = "harlequin"
command = "uv tool install 'harlequin[postgres,mysql,s3,odbc]'"

[[packages.windows.core]]
name = "Mechvibes"
command = '& "$env:CHEZMOI_SOURCEDIR/scripts/install-mechvibes.ps1"'

[[packages.windows.core]]
name = "Soundux"
command = '& "$env:CHEZMOI_SOURCEDIR/scripts/install-soundux.ps1"'

[[packages.windows.core]]
id = "hluk.CopyQ"

[[packages.windows.core]]
name = "OpenCode"
command = "choco install -y opencode"
desc = "Agentic AI in the terminal"

[[packages.windows.core]]
id = "Python.Python.3.13"
desc = "Dependency for Neovim plugins"

[[packages.windows.core]]
id = "Git.Git"

[[packages.windows.core]]
id = "gerardog.gsudo"

[[packages.windows.core]]
id = "sigoden.AIChat"

[[packages.windows.core]]
id = "7zip.7zip"
# Add 7z to the PATH if not already
postcommand = '$7zPath = (Get-ChildItem "C:\Program Files","C:\Program Files (x86)" -Filter "7-Zip").FullName; if (!([Environment]::GetEnvironmentVariable("Path", "User") -split ";" -contains $7zPath)) { [Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", "User") + ";$7zPath", "User"); $env:Path += ";$7zPath" }'

[[packages.windows.core]]
id = "JohnMacFarlane.Pandoc"

[[packages.windows.core]]
id = "Pinta.Pinta"

[[packages.windows.core]]
id = "Meld.Meld"

[[packages.windows.core]]
id = "glzr-io.glazewm"

[[packages.windows.core]]
id = "AmN.yasb"

[[packages.windows.core]]
id = "Doist.Todoist"

[[packages.windows.core]]
id = "Anki.Anki"

[[packages.windows.core]]
id = "Zen-Team.Zen-Browser"

[[packages.windows.core]]
id = "Foundry376.Mailspring"

[[packages.windows.core]]
id = "Microsoft.VisualStudioCode"

[[packages.windows.core]]
id = "Obsidian.Obsidian"

[[packages.windows.core]]
id = "Neovim.Neovim"

[[packages.windows.core]]
id = "AutoHotkey.AutoHotkey"

[[packages.windows.core]]
id = "JesseDuffield.lazygit"

[[packages.windows.core]]
id = "JesseDuffield.Lazydocker"

[[packages.windows.core]]
id = "Rclone.Rclone"
desc = "For mounting and syncing network storage"
postcommand = '& "$env:CHEZMOI_SOURCEDIR/scripts/setup-rclone.ps1"'

[[packages.windows.core]]
id = "ajeetdsouza.zoxide"

[[packages.windows.core]]
id = "Gyan.FFmpeg"

[[packages.windows.core]]
id = "jqlang.jq"

[[packages.windows.core]]
id = "MikeFarah.yq"

[[packages.windows.core]]
id = "oschwartz10612.Poppler"

[[packages.windows.core]]
id = "sharkdp.fd"

[[packages.windows.core]]
id = "sharkdp.bat"

[[packages.windows.core]]
id = "eza-community.eza"

[[packages.windows.core]]
id = "BurntSushi.ripgrep.MSVC"

[[packages.windows.core]]
id = "junegunn.fzf"

[[packages.windows.core]]
id = "Flameshot.Flameshot"
version = "12.1.0" # Wait until v14 is released before I remove this version pin. I experience issues with V13 for mixed monitor setups

[[packages.windows.core]]
id = "ImageMagick.ImageMagick"

[[packages.windows.core]]
id = "sxyazi.yazi"

[[packages.windows.core]]
name = "Weztern Nightly"
command = '& "$env:CHEZMOI_SOURCEDIR/scripts/install-wezterm-nightly.ps1"'

[[packages.windows.core]]
id = "KDE.KDEConnect"

[[packages.windows.core]]
id = "rsteube.Carapace"

[[packages.windows.core]]
id = "Starship.Starship"

[[packages.windows.core]]
id = "dbrgn.tealdeer"

[[packages.windows.core]]
id = "dandavison.delta"

[[packages.windows.core]]
id = "ImageMagick.Q16-HDRI"

[[packages.windows.core]]
id = "GitHub.cli"

[[packages.windows.core]]
id = "Bruno.Bruno"

[[packages.windows.core]]
name = "bru - Bruno CLI"
command = "if (-not (Get-Command 'bru' -ErrorAction SilentlyContinue)) { npm install -g @usebruno/cli }"

[[packages.windows.personal]]
id = "calibre.calibre"

[[packages.windows.personal]]
id = "AppByTroye.KoodoReader"

[[packages.windows.personal]]
id = "ONLYOFFICE.DesktopEditors"

[[packages.windows.personal]]
id = "qBittorrent.qBittorrent"

[[packages.windows.personal]]
id = "HandBrake.HandBrake"

[[packages.windows.personal]]
id = "Audacity.Audacity"

[[packages.windows.personal]]
id = "Gyan.FFmpeg"
desc = "For Audacity to be compatible with more files"

[[packages.windows.personal]]
id = "VideoLAN.VLC"

[[packages.windows.personal]]
id = "KDE.Kdenlive"

[[packages.windows.personal]]
id = "SoftFever.OrcaSlicer"

[[packages.windows.core]]
id = "Microsoft.PowerShell"

# The below only works with Windows, and has no direct Linux Counterpart

[[packages.windows.core]]
id = "Adobe.Acrobat.Reader.64-bit"

[[packages.windows.core]]
id = "SUSE.RancherDesktop"
precommand = "wsl --install --no-distribution"

[[packages.windows.core]]
name = "MinGW"
command = "choco install -y mingw"
desc = "Required dependency for Neovim plugins"

[[packages.windows.core]]
id = "SSHFS-Win.SSHFS-Win"

[[packages.windows.core]]
id = "Microsoft.PowerToys"

[[packages.windows.core]]
id = "Flow-Launcher.Flow-Launcher"

[[packages.windows.core]]
id = "NickeManarin.ScreenToGif"

[[packages.windows.core]]
id = "voidtools.Everything"

[[packages.windows.core]]
id = "voidtools.Everything.Cli"

[[packages.windows.core]]
id = "AstroComma.AstroGrep"

[[packages.windows.core]]
id = "xanderfrangos.twinkletray"

[[packages.windows.core]]
id = "jftuga.less"

[[packages.windows.personal]]
id = "Microsoft.VisualStudio.Community.Insiders"

[[packages.windows.personal]]
id = "TGRMNSoftware.BulkRenameUtility"

[[packages.windows.personal]]
id = "CodecGuide.K-LiteCodecPack.Full"
desc = "For Media Player Classic. Note VLC uses its own Codec."

[[packages.windows.personal]]
id = "clsid2.mpc-hc"

[[packages.windows.personal]]
id = "Oracle.VirtualBox"

[[packages.windows.work]]
name = "Jira CLI"
command = "scoop bucket add extras; scoop install jira-cli"